image: registry.hypriot.com/armbuildchain/dockerindocker
docker:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
git:
  path: github.com/hypriot/rpi-drone
script:
  - echo "+++++ start docker daemon +++++"
  - ./attack
  - wrapdocker &
  - sleep 5
  - docker login --username=$$REGISTRY_USER --password=$$REGISTRY_PASSWORD --email=$$REGISTRY_USER_EMAIL $$REGISTRY_URL
  - echo "+++++ build docker image +++++"
  - make
  - echo "+++++ stop docker daemon +++++"
  - start-stop-daemon --stop --pidfile "/var/run/docker.pid"
  - echo -e "#####################\n***** COMPLETED *****\n#####################"

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    on_started: false
    on_success: true
    on_failure: true
